### ISSUE TITLE
Support universal (fat) dsyms from issue #4 is not complete

### ISSUE THREAD

**Issue by 3nippo** [hamstergene/symbolicate-crash#6]
## Issue

With #5 changes we obtain all uuid-path pairs of debug symbols contained in DWARF file, but we don't specify which symbols we want to use when calling `atos` -- `atos` uses symbols for system machine architecture by default. 

From `man atos`:
```
GETTING SYMBOLS FOR A DIFFERENT MACHINE ARCHITECTURE
     It is possible to get symbols for addresses from a different machine architecture than the system on which atos is running.  For example, when running atos on an Intel-based system, one may wish
     to get the symbol for an address that came from a backtrace of a process running on an ARM device.  To do so, use the -arch flag to specify the desired architecture (such as i386 or arm) and
     pass in a corresponding symbol-rich Mach-O binary image file with a binary image of the corresponding architecture (such as a Universal Binary).
```

As result, we get wrong symbolicated crash dump if system machine architecture does not match machine architecture from crash dump.

## Solution

It seems like architecture label is compatible between`dwarfdump` and `atos`. So the fix is as follows:
1) Get architecture label from `dwarfdump` for each uuid of debug symbols
2) Pass architecture label to `atos` along with path to debug symbols

@ailinykh @hamstergene

**Comment by ailinykh** [comment]
@hamstergene review, please!

**Comment by hamstergene** [comment]
Merged :)
